add yml file

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -18,15 +18,15 @@ workflows:
           PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
           mkdir -p "$PROFILES_HOME"
           echo curveProfileNew | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
-      - name: Add signing certificate
-        script: |
-          set -e # exit on first failed command
+      # - name: Add signing certificate
+      #   script: |
+      #     set -e # exit on first failed command
 
-          echo curveCirtificate_new | base64 --decode > /tmp/curveCirtificateNew.p12
-          keychain initialize
-          keychain add-certificates \
-              --certificate /tmp/curveCirtificateNew.p12 \
-              --certificate-password hR4yMGtG
+      #     echo curveCirtificate_new | base64 --decode > /tmp/curveCirtificateNew.p12
+      #     keychain initialize
+      #     keychain add-certificates \
+      #         --certificate /tmp/curveCirtificateNew.p12 \
+      #         --certificate-password hR4yMGtG
       - name: Increment build number
         script: agvtool new-version -all $BUILD_NUMBER
       - name: Set up code signing settings on Xcode project
